spring:
  application:
    name: phonograph
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
      jadira:
        usertype:
          autoRegisterUserTypes: true
          javaZone: Asia/Shanghai
          databaseZone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://localhost:3306/phonograph?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1qaz@WSX
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
grpc:
  enableReflection: true
phonograph:
  machineId: 1
  message-ringsize: 1024 ##必须2的乘方
  mq-exchange-name: push
  mq-queue-name: default-message
  router-key: com.wuhaowen.push

