spring:
  application:
    name: operator
  data:
    mongodb:
      uri:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        min-idle: 0

    timeout: 3000
grpc:
  enableReflection: true
  port: 6666
tweeter:
  service-path: localhost:7666
